authorName: default
experimentName: helixer_lstm_test
trialConcurrency: 2
#maxExecDuration: 5h
maxTrialNum: 10000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_default.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, BOHB
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
trial:
  command: /home/felix-stiehler/git/HelixerPrep/helixerprep/prediction/LSTMModel.py -v -d /home/felix-stiehler/Desktop/data/eight_genomes/ -l 3 -u 320 -bs 24 -ps 12 -ln -att -attw 10 -nni
  codeDir: .
  gpuNum: 1
